In [75]:
import torch

In [76]:
x ,y =torch.tensor(3.0) , torch.tensor(2.0)
x + y, x * y,x /y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [77]:
#Matrix 
A = torch.tensor(torch.arange(20)).reshape(5,4)
A

C:\Users\ygx79\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [78]:
#转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [79]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [80]:
B.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [81]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

张量表示图像
3个轴对应于高，宽，通道
用于表示RGB

In [82]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [83]:
A = torch.arange(20, dtype=torch.float64).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]], dtype=torch.float64))

In [84]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]], dtype=torch.float64)

In [85]:
a = 2
X =torch.arange(24).reshape(2,3,4) 
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [86]:
A, A.sum(axis=1), A.sum(axis=1, keepdim=True)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([ 6., 22., 38., 54., 70.], dtype=torch.float64),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]], dtype=torch.float64))

In [87]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]], dtype=torch.float64)

In [88]:
x, y = torch.rand(4), torch.rand(4)
x, y, torch.dot(x,y.T)

(tensor([0.4481, 0.9888, 0.6148, 0.0160]),
 tensor([0.2479, 0.0754, 0.7103, 0.5860]),
 tensor(0.6317))

In [89]:
# matrix 
# shape [5,4] shape=2 axis:0,1
# shape [2,5,4]
# axis 0 [5,4]
# axis 1 [2,4]
# axis 2 [2,5]
a = torch.ones((2,5,4))
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [90]:
A=a.sum(axis=0)
A, A.shape

(tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 torch.Size([5, 4]))

In [91]:
A=a.sum(axis=[0,2])
A, A.shape

(tensor([8., 8., 8., 8., 8.]), torch.Size([5]))

### Auto Grad

In [92]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [93]:
x.requires_grad_(True)
x.grad

In [94]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [95]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [96]:
x.grad == 4 * x

tensor([True, True, True, True])

In [100]:
#x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([2., 2., 2., 2.])

In [101]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [102]:
x.grad.zero_()
y = x * x 
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [103]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [104]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [105]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [106]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [107]:
a.grad == d / a

tensor(False)