In [1]:
import torch
import torch.nn.functional as F
import torch.nn.modules 

In [2]:
a = torch.tensor([1, 2, 8, 16, 32])
a[a.argmax().item()], a[a.argmin().item()]

(tensor(32), tensor(1))

In [12]:
a = torch.rand(2,5)
a, a.argmax(), a.argmin()

(tensor([[0.0738, 0.2039, 0.9751, 0.6728, 0.0814],
         [0.8244, 0.2333, 0.6276, 0.6056, 0.8781]]),
 tensor(2),
 tensor(0))

In [3]:
logs = torch.rand(4, 10)
pred = F.softmax(logs, dim=1)
pred.shape

torch.Size([4, 10])

In [4]:
pred_label = pred.argmax(dim=1)
pred_label

tensor([2, 7, 5, 5])

In [5]:
logs.argmax(dim=1)

tensor([2, 7, 5, 5])

In [6]:
label = torch.tensor([9, 3, 2, 4])
correct = torch.eq(pred_label, label)
correct

tensor([False, False, False, False])

In [7]:
correct.sum().float().item()/4

0.0